[build]
  functions = "./netlify/functions"

[build.environment]
  REACT_APP_ADMIN_LOGIN = "admin"
  REACT_APP_ADMIN_PASSWORD = "Starlight#2024"
  REACT_APP_MAP_API_KEY = "pk.eyJ1Ijoia2t3b3JrIiwiYSI6ImNsdGZucnJnMjBhcTMyanBuaGxpMWdxZGUifQ.FWTmvhPBxzkXAibuT4k_CQ"
  MAIL_API_KEY = "787934F3EDA1952BCC3D49463EF7287CD75E6EC60CC65446E199D36826028F6A6E7FE2816431DC4452BCEF990C6B084F"
